M48
; DRILL file {KiCad 7.0.2-79-gd0069e0e1d} date Mon May  8 00:19:56 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-05-08T00:19:56+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.2-79-gd0069e0e1d
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1378
%
G90
G05
T1
X4.15Y-0.95
X4.15Y-4.35
X5.95Y-0.95
X5.95Y-4.35
T0
M30
